### ISSUE TITLE
Make installer compatible with new Dockerfile context

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode_Installer#48]
Before:
```
build: "./build"
```
After:
```
build:
    context: .
    dockerfile: ./build/Dockerfile
    image: "vpn.dnp.dappnode.eth:0.2.0"
```
