### ISSUE TITLE
Add network creation when installing dappnode

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode_Installer#97]
Due to https://github.com/dappnode/DNP_DAPPMANAGER/issues/655 , consider create the dappnode network `dncore_network` during installation.

This network creation during installation would simplify docker networking and allow using in `compose.yml` files `external: true` and `name:dncore_network`:
```
version: "3.9"
services:
  random:
    image: chentex/random-logger
    networks:
      - network99

networks:
  network99:
    name: dncore_network
    external: true
```
